"""Write proofs_numbers.tex: every Monte-Carlo / numerical check quoted in proofs_v1.tex, read from results/*.json."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
R = ROOT / "data" / "results"


def J(name):
    return json.load(open(R / name, encoding="utf-8"))


def pct(x, d=2):
    return f"{100 * x:.{d}f}\\%"


def main():
    c2 = J("c2_mc.json")
    c3 = J("c3_numbers.json")
    c4 = J("c4_power.json")
    va = J("validity_audit.json")
    ce = J("c2_empirical.json")["results"]
    c5 = J("c5a_monotone.json")
    m = {}
    row0 = [r for r in c2["grid"] if r["eps"] == 0.05 and r["delta"] == 0.05 and r["delta_prime"] == 0.05][0]
    m["ConeClosed"] = f"{row0['closed_form']:.4f}"
    m["ConeMC"] = f"{row0['mc']:.4f}"
    m["CtwoMaxDev"] = f"{c2['max_abs_dev_pp_exact']:.2f}"
    m["CtwoNgrid"] = str(len(c2["grid"]))
    m["CtwoAllMax"] = "yes" if c2["all_exact_maximal"] else "no"
    tw = ce["eps5_d32_K1"]["pools"]["S1_twin_main"]
    m["CtwoTwinPass"] = pct(tw["P_sim_pass"], 1)
    for dp, tag in (("0.075", "A"), ("0.1", "B"), ("0.15", "C"), ("0.2", "D")):
        d = tw["by_delta_prime"][dp]
        m[f"CtwoFC{tag}"] = pct(d["false_cert_at_p_eq_eps"], 1)
        m[f"CtwoCred{tag}"] = f"{d['realised_credit_events']:.1f}"
    m["CtwoBMCPass"] = pct(ce["eps5_d32_K1"]["pools"]["S0_BMC_Gstar"]["P_sim_pass"], 1)
    m["CthreeA"], m["CthreeB"], m["CthreeC"] = (str(r["n_real"]) for r in c3["rows"])
    lm = c4["lemma_mean_median"]
    m["LemmaMin"] = f"{lm['min_F_floor_Np']:.4f}"
    fv = c4["c4a_fleet_validity"]
    m["FleetPBmax"] = f"{max(v['exact_fail_poisson_binomial'] for v in fv.values()):.4f}"
    m["FleetMCmax"] = f"{max(v['mc_fail'] for v in fv.values()):.4f}"
    m["FleetNpat"] = str(len(fv))
    meas = [r for d in va["c4a_fleet"].values() for r in d.values() if "exact_fail_poisson_binomial" in r]
    m["FleetMeasPBmax"] = f"{max(r['exact_fail_poisson_binomial'] for r in meas):.4f}"
    m["FleetMeasMCmax"] = f"{max(r['mc_fail'] for r in meas):.4f}"
    m["FleetMeasN"] = str(len(meas))
    m["PopFailMax"] = f"{va['pop_theorem_check']['c4a_pop_max_fail']:.4f}"
    m["CfourbFailMax"] = f"{va['pop_theorem_check']['c4b_max_fail']:.4f}"
    m["PopScenesTen"] = str(c4["scenes_needed_c4a_pop"]["U<=0.1"])
    m["PopScenesFive"] = str(c4["scenes_needed_c4a_pop"]["U<=0.05"])
    ch = va["points"]["OP*"]["loso"]
    m["PopM"] = str(va["pop_theorem_check"]["m"])
    m["CtwoTwinN"] = str(ce["eps5_d32_K1"]["pools"]["S1_twin_main"]["N_sim"])
    m["LosoViolNum"], m["LosoViolDen"] = str(ch["violation_rate_D"]["num"]), str(ch["violation_rate_D"]["den"])
    m["CfiveAll"] = "yes" if c5["all_monotone"] else "no"
    t = c5["tables"]["d_min32"]["K16"]["q_by_x"]
    m["CfiveQzero"], m["CfiveQfifty"] = pct(t["0.0"]), pct(t["0.5"])
    lines = ["% generated by tools/make_proofs_numbers.py from results/*.json -- do not edit"]
    lines += [f"\\newcommand{{\\num{k}}}{{{v}}}" for k, v in m.items()]
    (ROOT / "proofs_numbers.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
