"""Write manuscript/supp_tables.tex: every supplementary table, generated from results/*.json (no hand-typed numbers)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
R = ROOT / "data" / "results"


def J(n):
    return json.load(open(R / n, encoding="utf-8"))


def P(x, d=1):
    return "--" if x is None else f"{100 * x:.{d}f}\\%"


def F(x, d=2):
    return "--" if x is None else f"{x:.{d}f}"


def tab(label, caption, cols, head, rows, small=True):
    L = [r"\begin{table}[H]", r"\centering", r"\caption{" + caption + "}", r"\label{" + label + "}"]
    if small:
        L.append(r"\small")
    L += [r"\begin{tabular}{@{}" + cols + "@{}}", r"\toprule", " & ".join(head) + r" \\", r"\midrule"]
    L += [" & ".join(str(c) for c in r) + r" \\" for r in rows]
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(L)


def longtab(label, caption, cols, head, rows):
    L = [r"\begin{longtable}{@{}" + cols + "@{}}", r"\caption{" + caption + r"}\label{" + label + r"}\\", r"\toprule",
         " & ".join(head) + r" \\", r"\midrule", r"\endfirsthead", r"\toprule", " & ".join(head) + r" \\", r"\midrule",
         r"\endhead", r"\bottomrule", r"\endlastfoot"]
    L += [" & ".join(str(c) for c in r) + r" \\" for r in rows]
    L += [r"\end{longtable}", ""]
    return "\n".join(L)


STEP_LABELS = ["first twin run, original definition (all events, all durations)",
               "first twin run, largest object $\\ge 256$ px",
               "same scenes, LASIESTA frames in true temporal order",
               "LASIESTA scene list rebuilt (20 to 48 scenes)",
               "pan-tilt-zoom scenes excluded (4)",
               "scenes run (2 held-out turbulence scenes not run)",
               "events of at least $d_{\\min}=32$ frames"]


def main():
    out = ["% generated by tools/make_supp_tables.py from results/*.json -- DO NOT EDIT"]
    wf = J("e0_event_waterfall.json")
    out.append(tab("tab:waterfall", "Event counts from the first twin run to the analysed set (primary definition: largest "
                   "object $\\ge 256$ px). The two headline counts differ in unit: all durations vs.\\ duration $\\ge 32$.",
                   "lrr", ["step", "events", "scenes"],
                   [(lab, s["events"], s["scenes"]) for lab, s in zip(STEP_LABELS, wf["steps"])]))
    u = J("e0_units.json")["recomputed"]
    rows = []
    for t in ("main", "night", "turbulence", "all_tiers"):
        for r in ("rule_1of3", "rule_2of3", "rule_3of3"):
            s = u[t][r]
            rows.append((t.replace("_", " "), r[5] + "/3", s["N_events"], s["D_worst_phase"]["num"], F(s["D_expected"]["num"]),
                         F(s["D_old_variant_mean"]["num"]), P(s["D_worst_phase"]["U_fleet"], 2), f"{s['J']['num']}/{s['J']['den']}",
                         P(s["J"]["U_pop"], 2)))
    out.append(tab("tab:rules", "Sprite-variant rule (twin catches if $\\ge r$ of 3 variants catch) at OP$^\\ast$: worst-phase "
                   "discordant events; phase-averaged count under the rule (exp.) and averaged over the three variants (var.\\ mean, "
                   "the parenthesised count of the main text); bounds.", "llrrrrrrr",
                   ["tier", "$r$", "$N$", "disc.", "exp.", "var.\\ mean", "$U(X,N)$", "$J/m$", "$U(J,m)$"], rows))
    ex = J("exchange_rate_v2.json")["grid"]
    rows = [(r["d_min"], r["K"], P(r["p_main"], 2), r["n_direct"] if r["n_direct"] is not None else "--",
             F(r["q_known"]["events_saved_per_camera"]["median"], 0), r["q_known"]["cameras_saving"],
             r["q_finite"]["cameras_saving"], F(r["q_known"]["cpu_hours_per_saved_event"]["median"], 3))
            for r in ex if r["eps"] == 0.20]
    out.append(r"\begingroup\footnotesize" + "\n" + longtab("tab:grid", "Full operating-point grid at $\\varepsilon=20\\%$ (78 static "
               "cameras): static-domain real miss rate, events for direct certification, median events saved per camera "
               "(twin run to convergence), cameras saving (converged / as built), CPU-hours per saved event.", "rrrrrrrr",
               ["$d_{\\min}$", "$K$", "$\\hat p$", "$n_{\\mathrm{dir}}$", "saved", "cams", "as built", "CPU-h"], rows)
               + r"\endgroup")
    m2 = J("must_fail_v2.json")["points"]
    for key, lab in (("OP*", "OP$^\\ast$"), ("challenge_16_16", "$(16,16)$ (post hoc)")):
        rows = [(t["video"], t["n"], P(t["p_s"]), P(t["p_detector"]), P(t["p_temporal"]), P(t["q_s"]), P(t["D_s"]),
                 t["worst_phase_discordant"], "yes" if m2[key]["night_with_main_only_calibration"][t["video"]]["false_cert"] else "no")
                for t in m2[key]["night_table"]]
        out.append(tab(f"tab:night{'OP' if key == 'OP*' else 'CH'}", f"Night scenes at {lab}: real miss rate split into detector "
                       "and temporal misses, twin miss rate, discordance, and whether the camera is falsely certified when "
                       "judged with a bound from the static scenes only.", "lrrrrrrrr",
                       ["scene", "$n$", "$p_s$", "detector", "temporal", "$q_s$", "$D_s$", "disc.", "false cert."], rows))
        rows = [(c["k"], c["n_subsets"], P(c["U_pop_median"]), f"{P(c['U_pop_min'])}--{P(c['U_pop_max'])}", P(c["U_fleet_median"]),
                 P(c["share_fleet_refused"], 0), c["main_false_cert_max"]) for c in m2[key]["curve"]]
        out.append(tab(f"tab:leak{'OP' if key == 'OP*' else 'CH'}", f"Must-fail 2 at {lab}: $k$ night scenes in the calibration set "
                       "(all subsets).", "rrrrrrr", ["$k$", "subsets", "$U_{\\mathrm{pop}}$ med.", "range", "$U_{\\mathrm{fleet}}$ med.",
                                                     "withdrawn", "static false cert."], rows))
    va = J("validity_audit.json")
    rows = []
    for k, v in va["must_fail"].items():
        for s in v["scenes_p_gt_eps"]:
            rows.append((k.replace("_", " "), s["video"].replace("_", "\\_"), s["n"], P(s["p"]), P(s["p_app"]), P(s["p_struct"]), P(s["q"])))
    out.append(tab("tab:mf1", "Must-fail 1 (temporal, $K=48$): static scenes with $p_s>\\varepsilon$; detector vs.\\ temporal "
                   "misses and twin miss rate. All were refused in every Monte-Carlo run.", "llrrrrr",
                   ["point", "scene", "$n$", "$p_s$", "detector", "temporal", "$q_s$"], rows))
    rows = []
    for k, v in va["points"].items():
        for s in v["loso"]["violating_scenes"]:
            rows.append((k.replace("challenge_16_16", "(16,16)").replace("OP*", "OP$^\\ast$"), s["video"].replace("_", "\\_"), s["n"],
                         P(s["D_s"]), P(s["p_s"]), P(s["q_s"]), P(s["U_pop_minus"]), "yes" if s["viol_C3"] else "no",
                         "yes" if s["false_cert"] else "no"))
    out.append(tab("tab:loso", "Leave-one-scene-out: scenes whose discordance exceeds the bound computed without them.", "llrrrrrrr",
                   ["point", "scene", "$n$", "$D_s$", "$p_s$", "$q_s$", "$U_{-s}$", "$p_s>q_s+U$", "false cert."], rows))
    iw = J("iw_ablation_v2.json")
    rows = []
    for lab, key in (("temporal", "a_temporal|logistic"), ("geometry", "b_geometry|logistic"), ("appearance only", "e_appearance_only|logistic")):
        rows.append((lab, F(iw["summary_all_targets"][key]["auc_median"]), F(iw["summary_cdnet_targets"][key]["auc_median"])))
    out.append(tab("tab:iw", "Synthetic-vs-real classifier (logistic), median AUC over target sets: all targets (main text) "
                   "and CDnet targets only.", "lrr", ["features", "all targets", "CDnet targets"], rows))
    geo = J("e0_geometry_sensitivity.json")["frame_level"]
    rows = [(k.split("/")[0], k.split("/")[1].replace("%", "\\%").replace("<=", "$\\le$").replace(">", "$>$"), v["n"],
             P(v["twin_hit"]), P(v["real_hit"]), F(100 * v["twin_minus_real"], 1)) for k, v in geo["by_kind_aspect"].items()]
    out.append(tab("tab:aspect", "Twin and real hit rates on the same frames by object kind and sprite aspect error (before the "
                   "width clamp).", "llrrrr", ["kind", "$|$aspect err.$|$", "frames", "twin hit", "real hit", "diff. (pts)"], rows))
    c5 = J("c5a_monotone.json")["tables"]
    rows = []
    for d in ("d_min32", "d_min16", "d_min1"):
        for K in ("K1", "K8", "K16", "K48"):
            q = c5[d][K]["q_by_x"]
            rows.append((d.replace("d_min", ""), K[1:], *(P(q[x], 2) for x in ("0.0", "0.1", "0.25", "0.5")),
                         "yes" if c5[d][K]["per_event_q_monotone"] else "no"))
    out.append(tab("tab:c5a", "C5a: twin miss rate when every event is shortened by $x$.", "rrrrrrr",
                   ["$d_{\\min}$", "$K$", "$x=0$", "10\\%", "25\\%", "50\\%", "per event monotone"], rows))
    ce = J("c2_empirical.json")["results"]
    rows = []
    for k, v in ce.items():
        for pn, pr in v["pools"].items():
            b = pr["by_delta_prime"]
            lab = {"eps5_d32_K1": "$\\varepsilon=5\\%$, (32,1)", "eps20_OPstar": "$\\varepsilon=20\\%$, OP$^\\ast$"}[k]
            sim = {"S0_BMC_Gstar": "BMC (G$^\\ast$)", "S0_BMC_T": "BMC (temporal)", "S1_twin_main": "paired twin"}[pn]
            rows.append((lab, sim, pr["N_sim"], P(pr["P_sim_pass"]),
                         "/".join(F(b[d]["realised_credit_events"], 1) for d in ("0.075", "0.1", "0.15", "0.2")),
                         "/".join(P(b[d]["false_cert_at_p_eq_eps"]) for d in ("0.075", "0.1", "0.15", "0.2"))))
    out.append(r"\begingroup\footnotesize" + "\n" + tab("tab:c2emp", "Empirical C2: two-tier procedure with each simulator "
               "(100{,}000 runs), $\\delta'=7.5/10/15/20\\%$.", "llrrll",
               ["point", "simulator", "$N_{\\mathrm{sim}}$", "pass", "credit (events)", "false cert.\\ at $p=\\varepsilon$"], rows, small=False)
               + r"\endgroup")
    # P4-final F1: worst-phase convention and site-level bound
    wp = J("worst_phase.json")["points"]
    rows = []
    for pt, lab in (("OP*", "OP$^\\ast$"), ("challenge_16_16", "$(16,16)$ post hoc")):
        for t in ("main", "night", "turbulence", "all_tiers"):
            r = wp[pt]["tiers"][t]
            rows.append((lab, t.replace("_", " "), r["N"], P(r["p_phase_avg"]), P(r["p_w"]), P(r["q_phase_avg"]), P(r["q_w"]),
                         r["D_w"], P(r["U_fleet"], 2), f"{r['J']}/{r['m']}", P(r["U_pop"], 2)))
            lab = ""
    out.append(r"\begingroup\footnotesize\setlength{\tabcolsep}{2pt}" + "\n" + tab("tab:worstphase", "Worst-phase convention (valid for any fixed deployment phase): real and twin miss rates averaged "
                   "over phases and at the worst phase, discordant events, fleet and population bounds.", "llrrrrrrrrr",
                   ["point", "tier", "$N$", "$\\hat p$ avg", "$\\hat p$ worst", "$\\hat q$ avg", "$\\hat q$ worst", "disc.",
                    "$U(X,N)$", "$J/m$", "$U(J,m)$"], rows, small=False) + r"\endgroup")
    rows = []
    for pt, lab in (("OP*", "OP$^\\ast$"), ("challenge_16_16", "$(16,16)$ post hoc")):
        x = wp[pt]["exchange_main"]
        rows.append((lab, P(x["p_main_worst"]), x["n_direct"], x["cameras_accepted"], F(x["saved_median"], 0),
                     x["false_accept"], F(x["n_twin_needed_median"], 0)))
    out.append(tab("tab:worstx", "Exchange rate under the worst-phase convention (78 static cameras; twin run to convergence).",
                   "lrrrrrr", ["point", "$\\hat p$ worst", "$n_{\\mathrm{dir}}$", "accepted", "saved", "false acc.", "twin runs"], rows))
    sb = J("site_bound.json")["points"]
    for pt, lab, key in (("OP*", "OP$^\\ast$", "OP"), ("challenge_16_16", "$(16,16)$ post hoc", "CH")):
        r = sb[pt]["main"]
        lo = {x["site"]: x for x in r["loso"]}
        rows = [(x["site"].replace("_", "\\_").replace("CDnet:", "CDnet ").replace("LASIESTA:", "LASIESTA "), x["scenes"], x["n"],
                 int(x["disc"]), P(lo[x["site"]]["U_minus"]), "yes" if lo[x["site"]]["viol"] else "no") for x in r["sites"]]
        out.append(tab(f"tab:site{key}", f"Site-level population bound at {lab}: {r['m_site']} sites, $J_{{\\mathrm{{site}}}}={r['J_site']}$, "
                       f"$U(J_{{\\mathrm{{site}}}},m_{{\\mathrm{{site}}}})={P(r['U_pop_site'])}$; per site: scenes, events, discordant events, "
                       "bound without the site, leave-one-site-out violation.", "lrrrrl",
                       ["site", "scenes", "events", "disc.", "$U_{-\\mathrm{site}}$", "violation"], rows))
    (ROOT / "manuscript" / "supp_tables.tex").write_text("\n".join(out), encoding="utf-8")
    print("[write] supp_tables.tex", len(out) - 1, "tables")


if __name__ == "__main__":
    main()
